### ISSUE TITLE
Inconsistent use of vep and vep_file in run_eggla_gwas()

### ISSUE THREAD

**Issue by burrowsk** [mcanouil/eggla#101]
### Bug description

The parameter to add the path to a VEP annotation file is `vep` within `run_eggla_gwas()` [line 95]. the parameter `vep` is called in line 443 `vep_file = vep`, however, all other instances specify `vep_file` which causes the function to exit upon the first instance [lines 408-423].
Only applicable should a user want to specify a vep file.

```
if (nzchar(system.file(package = "future.apply"))) {
    eggla_lapply <- function(X, basename_file, vep_file, bin_path, bcftools_view_options, build, strand, info_type, FUN) {
      future.apply::future_lapply(
        X = X,
        basename_file = basename_file,
        vep_file = vep_file,
        bin_path = bin_path,
        bcftools_view_options = bcftools_view_options,
        build = build,
        strand = strand,
        info_type = info_type,
        future.globals = FALSE,
        future.packages = "data.table",
        FUN = FUN
      )
    }
```

### `eggla` version output

`eggla 0.18.5`

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment]
This is normal, "vep_file" is internal when defined `eggla_lapply`.
Although I simplified this and anyway renamed the main argument to be more consistent with syntax of other arguments.

I believe the issue you are having is somewhere else, _i.e._,
https://github.com/mcanouil/eggla/blob/1eb2dd56b4c0f883493f99e8d186425361ca4ffd/R/run_eggla_gwas.R#L449-L480

Note that the changes are in the current PR #97
