### ISSUE TITLE
Increase of number of iterations for the EM algorithm `niterEM`

### ISSUE THREAD

**Issue by burrowsk** [mcanouil/eggla#110]
Hi! 
We have been troubleshooting one cohort where the chosen model was not running without warnings. We managed to solve this by increasing the number of iterations for the EM algorithm used to refine the initial estimates of the random effects variance-covariance coefficients from the default of 25 to 100.
The nlme control variable is `niterEM`

Please could the increase in iterations be incorporated into the `egg_model()` function in order to `run_eggla_lmm()` to run for the cohort?

Thanks!

**Comment by mcanouil** [comment]
Because it's only for some cohorts, I set it in the first fall back model which now increases all kind of iterations in the optimiser.
This means no changes for all working cohort but should work for the one where it fails.
See #111 

Continuous integration tests are running, if all good, a new release is expected soon.

**Comment by mcanouil** [comment]
`v0.19.4` is being released.
The R package is already available.
Site and Docker image are building at this moment.

**Comment by burrowsk** [comment]
Sorry to reopen this :(
I have had a look at some results sent after the update and noticed that the results were not as expected (from testing the EM iterations with the cohort) and match those from previous models we were concerned about. 

It's my fault, I didn't consider warnings as well as errors when reviewing the update. I guess the model moves to increase the EM iterations on error message only? Is it possible to include warning messages?

Thanks.

**Comment by mcanouil** [comment]
I see, it was not an error.
Ok, I'll make some change.

**Comment by burrowsk** [comment]
Yes, sorry about that I didn’t think properly about error vs. warning ☹.

------------------------------------------------------------------

Dr. Kimberley Burrows
Senior Research Associate in Epidemiology
Centre for Academic Child Health
Bristol Medical School
University of Bristol

Email: ***@***.******@***.***>
http://www.bristol.ac.uk/medical-school/
Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>

Top 10 UK university and 61st in the world (QS Rankings 2023)
Top 5 UK university for research (THE analysis of REF 2021)
4th most targeted university by top UK employers (High Fliers 2023)

My pronouns are she/her
