### ISSUE TITLE
ID ordering differences regarding eggla_aucs() and eggla_slopes() 

### ISSUE THREAD

**Issue by DrGengWang** [mcanouil/eggla#127]
### Bug description

Thank you for the recent update to version 1.0.2! I tested both eggla_slopes() and eggla_aucs() functions and successfully matched data to the correct IDs, even when the input dataset wasn’t ordered by ID. I’ve attached the output of the .qmd and simulated data for your reference. The test was run on R version 4.4.1 (2024-06-14) and macOS 14.3.

[Test eggla v1.0.2.pdf](https://github.com/user-attachments/files/17697845/Test.eggla.v1.0.2.pdf) 

[test_data_full.txt](https://github.com/user-attachments/files/17697868/test_data_full.txt)
[test_data_reduced.txt](https://github.com/user-attachments/files/17697867/test_data_reduced.txt)

However, I have two minor comments:

1. ID Ordering Differences
The output from eggla_slopes() reorders the IDs (e.g., 1, 10, 100, 2…), while eggla_aucs() retains the input data order (e.g., 1, 2, 3, 4…). Though the IDs still align with the correct predictions and phenotypes, this discrepancy seems to arise from how each function combines the IDs with predicted values:

In eggla_aucs(): the command out <- cbind.data.frame(Row.names = rownames(pred_auc), pred_auc) is used.
In eggla_slopes(): the command out <- merge(x = pred, y = slopes, by = "row.names") is used.

Would it be possible to update eggla_auc() to use merge() to match eggla_slopes()?

I haven’t tested run_eggla_lmm() as it appears to be a wrapper for eggla_slopes() and eggla_aucs(), likely using merge() by ID to combine the outcomes. For reference, class(slopes$ID) is "AsIs" while class(aucs$ID) is "character". Based on the code, run_eggla_lmm() appears to merge by ID, so it shouldn't affect the final output.

2. Warning on Reduced Knot Points
With fewer knot points, the following warning may appear, although it doesn’t affect the output:

“In coeff * c(x1^0, x1^1, x1^2, x1^3, (x1 - knots)^3)/c(1, ... : longer object length is not a multiple of shorter object length”

The warning originates from line 86 in egg_slopes.R (https://github.com/mcanouil/eggla/blob/main/R/egg_slopes.R). The denominator c(1, 1, 2, rep(6, 4)) has 7 elements, but the numerator has fewer elements when fewer knots are used. This occurs specifically in the command:

y1_tmp <- coeff * c(x1^0, x1^1, x1^2, x1^3, (x1 - knots)^3) / c(1, 1, 2, rep(6, 4))

It doesn’t impact the final calculation: y1 <- sum(y1_tmp[seq_len(4 + findInterval(x1, knots, left.open = TRUE))]). The same issue is present in y2_tmp on line 92 and in line 77 of egg_aucs() (https://github.com/mcanouil/eggla/blob/main/R/egg_aucs.R).

To prevent the warning, could we update the code as follows:

y1_tmp <- coeff * c(x1^0, x1^1, x1^2, x1^3, (x1 - knots)^3) / c(1, 1, 2, rep(6, (length(knots)+1)))

If an analyst sets options(warn) to something other than the default (0), this warning could be flagged as an error. Analysts can check and reset this option with getOption("warn") and options(warn = 0) as needed.

Thank you for considering these suggestions!

### `eggla` version output

1.0.2

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment]
> Would it be possible to update eggla_auc() to use merge() to match eggla_slopes()?

Thanks for noticing, although I will go the other way around, i.e., disable sorting of the keys in merge (I forgot those was the default).

> Warning on Reduced Knot Points
With fewer knot points, the following warning may appear, although it doesn’t affect the output

Thanks for catching that. Warnings are bad so I will definitely update the formula to be dynamic based on the number of knots.
