### ISSUE TITLE
Concordance of dataframe name for Daymont and non-Daymont datasets

### ISSUE THREAD

**Issue by burrowsk** [mcanouil/eggla#4]
Hi,
There is a very minor issue of data frame naming when following the pipeline according to the README. Could the resulting data frame from Daymont cleaning (`visits_clean`) be instead named `pheno_dt`?  
The pipeline calls on `pheno_dt` and therefore does not use `visits_clean`. The result is no filtering of observations and missing data in BMI giving errors when plotting residuals. 

Thanks!

```r
# insert reprex here
```

**Comment by mcanouil** [comment]
Indeed, there was an inconsistency from the update to focus on the selected model.
Readme is now consistent whether with Daymont's QC or not, _i.e., it produces `pheno_dt_clean` object.
