### ISSUE TITLE
Ensure GWAS output is consistent with analysis plan

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/eggla#48]
| Column Header     | Description                                                                                  | Format                                                                                              | Examples        |
|:------------------|:---------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------|:----------------|
| SNPID             | SNP/INDEL ID label from the imputation server, or from directly genotyped data               | Text                                                                                                | 4:10229 / rs693 |
| STRAND            | Orientation of the site to the human genome strand used                                      | + (Should be aligned to the forward strand)                                                         | +               |
| BUILD             | Build of the genome on which the SNP is orientated                                           | Numeric                                                                                             | 37              |
| CHR               | Chromosome on which the SNP resides                                                          | Numeric                                                                                             | 1               |
| POS               | Position of SNP on                                                                           | Base pairs on human genome build used                                                               | 34000345        |
| EFFECT_ALLELE     | Allele for which the effect (BETA) is reported                                               | SNP: Capital letter (A,C,G,T) / INDEL: Allele output by imputation server                           | A               |
| NON_EFFECT_ALLELE | Other allele at this site                                                                    | SNP: Capital letter (A,C,G,T) / INDEL: Allele output by imputation server                           | G               |
| N                 | Total number of samples analysed at this site                                                | Numeric, integer                                                                                    | 1234            |
| N0                | Number of homozygous samples with zero copies of the EFFECT_ALLELE                           | Numeric, integer or float with 4 digits to the right of the decimal (imputed)                       | 623 / 745.2345  |
| N1                | Number of heterozygous samples with one copy of the EFFECT_ALLELE                            | Numeric, integer or float with 4 digits to the right of the decimal (imputed)                       | 623 / 745.2345  |
| N2                | Number of homozygous samples with two copies of the EFFECT_ALLELE                            | Numeric, integer or float with 4 digits to the right of the decimal (imputed)                       | 623 / 745.2345  |
| EAF               | Allele frequency of the EFFECT_ALLELE                                                        | Frequency with 4 digits to the right of the decimal                                                 | 0.3546          |
| HWE_P             | Exact HWE p-value for samples analysed, only if genotyped data is used in analysis           | Scientific E notation with 4 digits to the right of the decimal (set to missing for imputed | SNPs) | 1.122E-02 / .   |
| CALL_RATE         | Genotyping call rate for the SNP (N_successful/N_attempted)                                  | Frequency 4 digits to the right of the decimal. Set to 1.000 if imputed                             | 0.9936          |
| BETA              | Estimate of the effect size                                                                  | Numeric float with 4 digits to the right of the decimal                                             | 0.2036          |
| SE                | Estimated standard error on the estimate of the effect size, uncorrected for genomic control | Numeric float with 4 digits to the right of the decimal                                             | 0.5611          |
| PVAL              | P value of the variant association                                                           | Scientific E notation with 4 digits to the right of the decimal                                     | 3.244E-10       |
| IMPUTED           | Is the SNP/INDEL imputed?                                                                    | 0 = Genotyped / 1 = Imputed                                                                         | 1               |
| INFO_TYPE         | Type of information provided in the INFO column                                              | Text, (set to missing if genotyped)                                                                 | impute_info     |
| INFO              | Measure of information content for the imputed SNP result                                    | Numeric float with 4 digits to the right of the decimal (set to missing if genotyped)               | 0.4832 / .      |

**Comment by mcanouil** [comment]
@burrowsk @3Aannihei For now and by default (`use_info = FALSE`) "INFO" is no longer extracted in `run_eggla_gwas()` (9c31a75e0bf8a639d8d6e7b192f8477e453a6fdd).
This will speed up computation, but won't produce the above output.

**Comment by burrowsk** [comment]
Thanks Mikael, I will do a test tun in ALSPAC. I’m now actually utilising parallel for the GWAS so the total run time is now only ~13 Hrs and not a week haha

BW, Kim

------------------------------
Dr. Kimberley Burrows
Senior Research Associate in Epidemiology
MRC Integrative Epidemiology Unit
Population Health Sciences
Bristol Medical School
University of Bristol
Room OS1
Oakfield House, Oakfield Grove, Bristol, BS8 2BN

Email: ***@***.***

http://www.bristol.ac.uk/integrative-epidemiology/
Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>

A top 3 UK university with leading employers (High Fliers 2017)
A top 5 UK university for research (REF 2014)
A world top 50 university (QS Ranking 2016)

My pronouns are she/her

**Comment by mcanouil** [comment]
I'll release eggla `v0.13.0` soon, I am waiting for some continuous integration workflows/tests to complete first.

**Comment by mcanouil** [comment]
Closed with be4fcc767aecaa31e84b9f3b5a5091b8ce71ea93 and #72

**Comment by burrowsk** [comment]
Cheers, will wait for release.

------------------------------
Dr. Kimberley Burrows
Senior Research Associate in Epidemiology
MRC Integrative Epidemiology Unit
Population Health Sciences
Bristol Medical School
University of Bristol
Room OS1
Oakfield House, Oakfield Grove, Bristol, BS8 2BN

Email: ***@***.***

http://www.bristol.ac.uk/integrative-epidemiology/
Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>

A top 3 UK university with leading employers (High Fliers 2017)
A top 5 UK university for research (REF 2014)
A world top 50 university (QS Ranking 2016)

My pronouns are she/her

**Comment by mcanouil** [comment]
Already released (6 days ago) 😉
