### ISSUE TITLE
run_eggla_gwas: Error in colnames

### ISSUE THREAD

**Issue by annihei** [mcanouil/eggla#49]
### Bug description

I created lmm results with

```r
results_archives <- run_eggla_lmm(
  data = fread("selected_cleaned_data.csv"),
  id_variable = "ID",
  age_days_variable = NULL,
  age_years_variable = "age",
  weight_kilograms_variable = "weight",
  height_centimetres_variable = "height",
  sex_variable = "sex",
  covariates = NULL,
  male_coded_zero = FALSE,
  random_complexity = 2,
  knots=c(1,8,12),
  parallel = FALSE,
  parallel_n_chunks = 1
)
```

and this worked fine. Next, tried the GWAS with the following error:

```r
run_eggla_gwas(
  data = "selected_cleaned_data.csv",
  results = results_archives,
  id_column = "ID",
  traits = c("slope_.*"),
  covariates = c("sex"),
  vcfs = list.files(
    path = file.path("/genetic_files", "vcf"),
    pattern = "\\.vcf$|\\.vcf.gz$",
    full.names = TRUE
  ),
  path = output_path,
  vep = NULL,
  bin_path = list(
    bcftools = "/usr/local/bin/bcftools",
    plink2 = "/usr/local/bin/plink2"
  ),
  threads = 1
)
#> Formatting VCFs ...
#> Writing trait results ...
#> Error in colnamesInt(x, neworder, check_dups = FALSE) :
#>   argument specifying columns specify non existing column(s): cols[1]='trait_model'
#> In addition: Warning message:
#> In run_eggla_gwas(data = "selected_cleaned_data.csv", results = results_archives,  :
#>   Sex must be coded: '1'/'M'/'m' = male, '2'/'F'/'f' = female, 'NA'/'0' = missing! '0' have been recoded as '2', i.e., female.
```
Looking at the code I don't see if trait_model was defined after setting it to NULL?

Regarding the warning: could the default coding for sex be the same as in the other functions: 0=female, 1=male?

```r
xfun::session_info()
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.5 LTS
#> 
#> Locale:
#>   LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
#>   LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
#>   LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
#>   LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C
#> 
#> Package version:
#>   assertthat_0.2.1    backports_1.4.1     bayestestR_0.12.1
#>   BH_1.75.0.0         bit_4.0.4           bit64_4.0.5
#>   broom_1.0.0         broom.mixed_0.2.9.4 cli_3.3.0
#>   clipr_0.8.0         coda_0.19.4         codetools_0.2-18
#>   colorspace_2.0-3    compiler_4.2.1      cpp11_0.4.2
#>   crayon_1.5.1        data.table_1.14.2   datawizard_0.5.1
#>   DBI_1.1.1           digest_0.6.29       doParallel_1.0.17
#>   dplyr_1.0.9         eggla_0.12.3        ellipsis_0.3.2
#>   fansi_1.0.3         farver_2.1.1        forcats_0.5.2
#>   foreach_1.5.2       furrr_0.3.1         future_1.27.0
#>   future.apply_1.9.0  generics_0.1.3      ggplot2_3.3.6
#>   globals_0.16.0      glue_1.6.2          graphics_4.2.1
#>   grDevices_4.2.1     grid_4.2.1          growthcleanr_2.0.0
#>   gtable_0.3.0        haven_2.5.1         hms_1.1.2
#>   insight_0.18.2      isoband_0.2.5       iterators_1.0.14
#>   labeling_0.4.2      labelled_2.9.1      lattice_0.20-44
#>   lifecycle_1.0.1     listenv_0.8.0       magrittr_2.0.3
#>   MASS_7.3.53         Matrix_1.3-3        methods_4.2.1
#>   mgcv_1.8-35         munsell_0.5.0       nlme_3.1-152
#>   parallel_4.2.1      parallelly_1.32.1   patchwork_1.1.2
#>   performance_0.9.2   pillar_1.8.1        pkgconfig_2.0.3
#>   plyr_1.8.7          prettyunits_1.1.1   progress_1.2.2
#>   purrr_0.3.4         R6_2.5.1            RColorBrewer_1.1.3
#>   Rcpp_1.0.9          readr_2.1.2         rlang_1.0.4
#>   rstudioapi_0.13     scales_1.2.1        splines_4.2.1
#>   stats_4.2.1         stringi_1.7.8       stringr_1.4.1
#>   tibble_3.1.8        tidyr_1.2.0         tidyselect_1.1.2
#>   tools_4.2.1         tzdb_0.3.0          utf8_1.2.2
#>   utils_4.2.1         vctrs_0.4.1         viridisLite_0.4.1
#>   vroom_1.5.7         withr_2.5.0         xfun_0.20
```

### `eggla` version output

```r
packageVersion('eggla')
#> [1] ‘0.12.3’
````

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment]
Thanks for reporting this here.
I have some ideas about what the issue is, I need first to reproduce it on my side.

Do you have the same error if you run the following example script: <https://github.com/mcanouil/eggla/blob/main/inst/setup/eggla-example.R> ?

**Comment by annihei** [comment]
I found an error in my vcfs file list path so I assume the original problem was that my vcf file list was empty. The script you linked works with the correct vcf paths. I tested it with just two chromosomes so it went through in a couple of hours (the result files refer to chromosomes 1 and 10 when I tested with 21 and 22, but I assume usually this would be done with all chromosomes).

**Comment by mcanouil** [comment]
Ok, so you don't know yet, if it's working?

By the way, I just added a check to ensure some individuals are present between the VCFs and the phenotypes.
I am going to add some other sanity check earlier, to have better error messages.

**Comment by annihei** [comment]
I tried it with correct vcf paths, and I think the original error was for my own mistake, sorry. The analysis started running, but was stopped with some error messages on "no space left on the device". I'll check with our maintainer here and get back to you if I can't proceed. 

I think some checks on sample size and number of variants or so would help!

**Comment by mcanouil** [comment]
"no space left on the device" might be due to small "scratch" space, I am working to allow to write temp files not in the default temp directory which should solve this.

**Comment by mcanouil** [comment]
@annihei `working_directory` can be set to something else than `tempdir()` and you can disable the cleaning process by setting `clean = FALSE` in the `run_eggla_gwas()` function. (59cdaf119ffbb666c82bc2345d6c4428cd278a23)

**Comment by annihei** [comment]
Cool I'll test this again!
