### ISSUE TITLE
Error in renv::init(base = TRUE) 

### ISSUE THREAD

**Issue by burrowsk** [mcanouil/eggla#6]
In run_eggla.sh script (and interactive code) the line (14):

`  -e 'renv::init(base = TRUE)' \`

results in error:

> renv::init(base = TRUE) 
Error in renv::init(base = TRUE) : unused argument (base = TRUE) 
Traceback (most recent calls last): 
3: renv::init(base = TRUE) 
2: renv_dots_check(...) 
1: stop(err) 

should the line instead be?:

`  -e 'renv::init(bare = TRUE)' \`

**Comment by mcanouil** [comment]
@burrowsk thanks!
Typos have been fixed. => `v0.4.2` (although, only the README changed)
