### ISSUE TITLE
Incorrect parameter correlations

### ISSUE THREAD

**Issue by burrowsk** [mcanouil/eggla#88]
### Bug description

I noticed that my correlations between the parameters were quite different from previous analyses. For instance using the derived-slopes.csv from `run_eggla_lmm()` for bmigrowth females, the correlations (using `stats::cor`) are:  

| term           | slope_0--0.5       | slope_1.5--3.5     | slope_6.5--10     | slope_12--17       |
|----------------|--------------------|--------------------|-------------------|--------------------|
| slope_0--0.5   | 1                  | 0.991665022459947  | 0.308438879534697 | -0.685332215016685 |
| slope_1.5--3.5 | 0.991665022459947  | 1                  | 0.428429069334579 | -0.585792675893659 |
| slope_6.5--10  | 0.308438879534697  | 0.428429069334579  | 1                 | 0.481341973221797  |
| slope_12--17   | -0.685332215016685 | -0.585792675893659 | 0.481341973221797 | 1                  |

The correlations for the same data given in derived-parameters-correlations.csv are:

| term           | slope_0--0.5 | slope_1.5--3.5 | slope_6.5--10 | slope_12--17 |
|----------------|--------------|----------------|---------------|--------------|
| slope_0--0.5   | 1            | 0.96025        | 0.02945       | -0.48586     |
| slope_1.5--3.5 | 0.96025      | 1              | 0.307301      | -0.22257     |
| slope_6.5--10  | 0.02945      | 0.307301       | 1             | 0.859348     |
| slope_12--17   | -0.48586     | -0.22257       | 0.859348      | 1            |

I think the issue becomes apparent in the following code block of `run_eggla_lmm()`

```r
      eggc_dt <- Reduce(
        f = function(x, y) merge(x, y, by = names(results$groups)),
        x = lapply(
          X = list(
            slopes_dt,
            aucs_dt,
            apar_dt
          ),
          FUN = function(data) {
            data <- data.table::setnames(data, "egg_id", names(results$groups), skip_absent = TRUE)
            data[grep(paste0("^auc_|^slope_|^AP_|^AR_|^", names(results$groups), "$"), names(data))]
          }
        )
      )

```

Object `eggc_dt` results in a reduced dataframe of the expected 13 variables but for only 5 individuals. This should be for all ~50 females right?

*Example code run*
```r
data("bmigrowth")
fwrite(x = bmigrowth, file = "bmigrowth.csv")
results <- run_eggla_lmm(
     data = fread("bmigrowth.csv"),
     id_variable = "ID",
     age_days_variable = NULL,
     age_years_variable = "age",
     weight_kilograms_variable = "weight",
     height_centimetres_variable = "height",
     sex_variable = "sex",
     covariates = NULL,
     random_complexity = 2
  )

slopes <- read.csv("derived-slopes.csv")
eggc <- data.table::as.data.table(
  x = stats::cor(slopes[grep("^slope_", names(slopes))]),
  keep.rownames = "term"
)
```

### `eggla` version output

> packageVersion('eggla')
[1] ‘0.18.0’

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment]
There were two issues:
1. Instead of selecting a subset of columns (1 to 4 mostly), a subset of rows were taken -> fixed by selecting only at the end.
2. When merging the parameters tables, if a missing value existed for an individual, all parameters were omitted -> fixed by requesting to keep all in the merge and by setting `"pairwise.complete.obs"` method to compute correlations between parameters.

To note, these issues were in `egg_correlations()` and `run_eggla_lmm()`.

**Comment by burrowsk** [comment]
Thanks Mickael, I was really struggling to figure it out!

------------------------------
Dr. Kimberley Burrows
Senior Research Associate in Epidemiology
MRC Integrative Epidemiology Unit
Population Health Sciences
Bristol Medical School
University of Bristol
Room OS1
Oakfield House, Oakfield Grove, Bristol, BS8 2BN

Email: ***@***.***

http://www.bristol.ac.uk/integrative-epidemiology/
Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>

A top 3 UK university with leading employers (High Fliers 2017)
A top 5 UK university for research (REF 2014)
A world top 50 university (QS Ranking 2016)

My pronouns are she/her

**Comment by mcanouil** [comment]
`v0.18.2` should be released thus "officially" available later tomorrow, once the the GitHub Actions will be completed.

**Comment by burrowsk** [comment]
Awesome, thanks :)

------------------------------
Dr. Kimberley Burrows
Senior Research Associate in Epidemiology
MRC Integrative Epidemiology Unit
Population Health Sciences
Bristol Medical School
University of Bristol
Room OS1
Oakfield House, Oakfield Grove, Bristol, BS8 2BN

Email: ***@***.***

http://www.bristol.ac.uk/integrative-epidemiology/
Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>

A top 3 UK university with leading employers (High Fliers 2017)
A top 5 UK university for research (REF 2014)
A world top 50 university (QS Ranking 2016)

My pronouns are she/her
