### ISSUE TITLE
Release `eggla` `v1.0.0`

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/eggla#90]
`eggla` `v1.0.0`[^1] should be released either upon manuscript submission (or when the analytical plan will be made available to the whole consortium).

- Update release date with `v1.0.0` release date (https://github.com/mcanouil/eggla/blob/main/CITATION.cff#L11)

  ```r
  cffr::cffr::cff_write()
  ```

[^1]: `v0.*.*` versions are for "beta" or "work in progress" software/tool, whilst `v1.*.*` or later major versions means the software has all the main features it should have for a stable/production use. See <https://semver.org/> for more details on semantic versioning.

**Comment by burrowsk** [comment]
Understood. Thanks for sending the link to details.

**Comment by mcanouil** [comment]
It's mostly a reminder to me. 😉

**Comment by burrowsk** [comment]
😊

------------------------------
Dr. Kimberley Burrows
Senior Research Associate in Epidemiology
MRC Integrative Epidemiology Unit
Population Health Sciences
Bristol Medical School
University of Bristol
Room OS1
Oakfield House, Oakfield Grove, Bristol, BS8 2BN

Email: ***@***.***

http://www.bristol.ac.uk/integrative-epidemiology/
Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>

A top 3 UK university with leading employers (High Fliers 2017)
A top 5 UK university for research (REF 2014)
A world top 50 university (QS Ranking 2016)

My pronouns are she/her

**Comment by mcanouil** [comment]
@burrowsk @nwarrington Upon the manuscript submission. We should bump the version to 1.0.0 (which means stable version and no longer "work in progress").

**Comment by mcanouil** [comment]
FYI: https://github.com/mcanouil/eggla/releases/tag/v1.0.0
