### ISSUE TITLE
N and EAF definition

### ISSUE THREAD

**Issue by annihei** [mcanouil/eggla#96]
### Bug description

I noticed a while ago that run_eggla_gwas output gives N, N0, N1 and N2 results using the total genotyped sample instead of the actual analysed sample which has both genotype + phenotype. We've had also the OBS_CT field from PLINK in the results, so this was not critical as the actual sample size was also in the summary stats. However, related to the meta-analysis we use the minor allele count for filtering the results, and related to this I did some check ups on how well the MAC and MAF from genotyped sample agrees with the values from the actual analysed sample. I found some really large differences between these in some SNPs, which made me go to the vcf files to see what was going on as I couldn't see from the run_eggla_gwas or my own codes an apparent explanation to this. I did my calculations on SNPtest because I couldn't work out how to select the subject IDs on bcftools. 

Seems like in run_eggla_gwas that part of the summary stats that come from bcftools are calculated based on the total genotyped sample, and EAF is counted using the GT field in vcf files whereas in the regression analyses we use the dosage DS. Could we have all of the summary stats, including Ns, EAF and HWE_P to be based on the actual analysed sample, and EAF using the dosage? Already thinking of the QC for the meta-analysis, also the extra fields in results that are not stated in the analysis plan, i.e. T_STAT,OBS_CT,ERRCODE,FDR,BONFERRONI could be also dropped out. 

### `eggla` version output

```
eggla_0.18.2
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment]
@Ning-L Could you try to take a look? (I'll see if I manage to work on this using the internal example dataset.)

It might be possible to get the proper statistics from PLINK which could solve the issue.

FYI, the "incriminating" part of the code is the following:
https://github.com/mcanouil/eggla/blob/3e7276472af0fdb9ff3f5b66fe5f63618c97afbc/R/run_eggla_gwas.R#L495-L571

**Comment by Ning-L** [comment]
Hi @mcanouil and Anni, I can not check it immediately since I'm on leave from next week until the first week of March, will have a look when I'm back.

**Comment by mcanouil** [comment]
@mboissel maybe?

**Comment by mboissel** [comment]
> @mboissel maybe?

Hello @mcanouil ,
I don't know if I will have time to look at this development this month, I'll come back to you if I do.
Do not hesitate to share here a chunk of code that you want to test as solution, I could try to apply it and make you the feed back.

**Comment by annihei** [comment]
@mcanouil Does it help if we would drop N0, N1 and N2 from the required summary stats? I think we can count MAC with sufficient accuracy based on the EAF and the analysed N, both of which I think should be in the PLINK glm results. Then there would be just the HWE_P left from those columns we currently get from bcftools. I am not sure if that is also estimated based on the total genotyped sample or the subset we have with phenotype, but I could also try to explore this with NFBC.

**Comment by mcanouil** [comment]
Well that's the actual question, go through the documentation and figure out what is computed from what.
`eggla` has a fake set of VCF for few variants/individuals.
My issue is mostly that I need to spend some time to get back to the documentation and try it out on the example dataset.

**Comment by annihei** [comment]
A small update in case you are planning to have a look at this next week. We discussed about the issue and the needed summary stats on the analyst call this week and Nicole brought a question if we even need the HWE_P in our results as the cohorts should have filtered on this before the imputation. We are going to discuss about this within the meta-analysis team before making the final decision so I'll let you know hopefully early next week. 

I have been looking at PLINK2 documentation this week compared to the eggla code, and realised that also the alleles come from bcftools as EFFECT_ALLELE=ALT and NON_EFFECT_ALLELE=REF, right (lines 538-547)? This also came up in the call, so by default PLINK2 treats the minor allele as the effect allele and major allele as the non effect allele. As these might be different depending on the data, the actual effect allele is given in the PLINK2 output column A1.

**Comment by mcanouil** [comment]
My idea is, if possible, to actually extract all from PLINK2.
I do not recall exactly why I extracted some from BCFtools, but:
1. For OBE or my toy dataset, I did not noticed any differences (unfortunate).
2. Maybe PLINK2 did not provide some.

I'll try to make some time to check on this, this weekend.
If I manage to do something, it will stay as a PR until changes are confirmed.

**Comment by mcanouil** [comment]
To note, below is the default output from PLINK
<img width="947" alt="image" src="https://user-images.githubusercontent.com/8896044/218255049-28f69189-c7dd-4262-8ee0-75bab50627e0.png">

**Comment by mcanouil** [comment]
I added `--freq`, `--missing`, and `--hardy` from PLINK2.
This will now produce the following output:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/8896044/218257569-0244ed05-bb59-4d72-a024-de9154ec5e19.png">

Note that FDR, BONFERRONI, etc. columns are only there to allow individual cohorts to reuse "locally" the summary statistics.
It's not necessarily for use in the meta-analysis.
