### ISSUE TITLE
Update default value for compute_apar function

### ISSUE THREAD

**Issue by nwarrington** [mcanouil/eggla#98]
### Bug description

When predicting the age at adiposity peak and rebound in the cohorts, we found that the age at adiposity peak only had 4 or 5 values (e.g. 0.65, 0.7, 0.75, 0.8, 0.85years). This was causing issues when we then excluded outliers in some cohorts as all but one category was flagged as an outlier. The current default 'step' in the compute_apar() function is 0.05. Could we please change this to 0.01? This extra resolution seems to resolve the issues within the cohorts we have tested. 

The code that needs changing is as follows (version 0.18.5):

Current code: function (fit, from = c("predicted", "observed"), start = 0.25, end = 10, **_step = 0.05_**, filter = NULL) 
Updated code: function (fit, from = c("predicted", "observed"), start = 0.25, end = 10, **_step = 0.01_**, filter = NULL) 

### `eggla` version output

> packageVersion('eggla')
[1] ‘0.18.5’

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment]
I changed it everywhere and improved some internals related to that.
